### ISSUE TITLE
Suggestion: Captions as subtitles

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [marioortizmanero/spotify-music-videos#47]
Hello,

I was thinking that it might be cool to have the video's captions as subtitles. Especially when using the `--audiosync` option. Lyricwikia is nice, but those lyrics are separate from the video. While the captions are more or less synchronized to the music (when using --audiosync at least). I thought maybe there could be a option `--subs` to enable this. 
I've done some work on this and I got it semi-working:

```
diff --git a/vidify/youtube.py b/vidify/youtube.py
index 0297c6b..1048471 100644
--- a/vidify/youtube.py
+++ b/vidify/youtube.py
@@ -8,6 +8,7 @@ calling youtube-dl.
 """
 
 import logging
+import os
 from typing import Optional
 
 from youtube_dl import YoutubeDL, DownloadError
@@ -34,6 +35,8 @@ class YouTubeDLWorker(QThread):
 
         self.options = {
             'format': 'bestvideo',
+            'writesubtitles': True,
+            'allsubtitles': True,
             'quiet': not debug
         }
         if width is not None:
@@ -74,4 +77,19 @@ class YouTubeDLWorker(QThread):
                              str(e))
                 self.fail.emit()
             else:
-                self.success.emit(info['entries'][0]['url'])
+                sublangs = list(info['entries'][0]['subtitles'])
+                syslang = os.environ['LANG'][:2]
+
+                if syslang in sublangs:
+                    subs = info['entries'][0]['subtitles'][syslang][0]['url']
+
+                elif 'en' in sublang:
+                    subs = info['entries'][0]['subtitles']['en'][0]['url']
+
+                else:
+                    try:
+                        subs = info['entries'][0]['subtitles'][sublang[0]][0]['url']
+                    except IndexError:
+                        subs = None
+
+                self.success.emit(info['entries'][0]['url'],subs)
```

I added the options to download captions to the YoutubeDL options, this creates the 'subtitles'` entry in the `info` dictionary. Next I create a list of the available languages. Then I check if the system language is one of the available languages, if it is use that. If not, check if English is available, if that also isn't available, just use the first entry. If `sublang` is empty then there are no captions for the videos, and it will give a `IndexError` and set subs to `None`.

This should probably somewhere have an `if` statement to only do all this if `--subs` is enabled. Sadly, I have no idea how to do that. 

In any case `self.succes.emit` now emits both the video url and the subtitle url. It *should* now be possible to use something like this to enable the subtitles in python-vlc:
```
Media.add_options(f"sub-file={subs}")
```
I haven't yet figured out how to do the same in python-mpv, but it is probably possible because executing `mpv --sub-file=${url}` works in bash.

**Comment by marioortizmanero** [comment]
Hi Andrew!

This is definitely a very good idea. I had thought of doing this but I had forgotten about it, so it's good that you bring it up. There are two ways to do this:

## 1

When I originally thought of implementing this, I was thinking of using an already existent module so that the lyrics are synchronized with the video. That's assuming that the lyrics are obtained separately from the YouTube video. Most music videos in my experience don't have lyrics, so this greatly enlarges the lyrics database. I learned about SwSpotify in #10 for a different reason, but it also seems to have a module to sync the lyrics in real time: https://github.com/SwagLyrics/autosynch

I really don't know how it works, or if it's usable outside that repo, but it sounds really cool. The devs @SwagLyrics, @chriswang030 and @aadibajpai might shine some light about this. There's also another problem: the audio data provided to the module has been downloaded **beforehand**. If it were to be used in Vidify, it would have to be in real time, like what the Work In Progress [audio synchronization](https://github.com/vidify/audiosync) module does.

This could also be troublesome depending on the implementation, because Vidify already has an audio synchronization module which runs in the background, and could cause lag depending on the system Vidify runs on.

## 2

I actually didn't know that youtube-dl can also download subtitles! I haven't tried it out but it seems really easy to use in comparison to the first option.

Your code sketch is really helpful, thank you. To make it easier to implement in other players (maintaining modularity is important), I would add a `subtitles` method inside the players (and in the generic player in `vidify.player.generic`) to handle subtitles inside them, and then managed by the MainWindow when `on_youtubedl_success` is called.

**Comment by AndrewAmmerlaan** [comment]
> ## 1
> 
> When I originally thought of implementing this, I was thinking of using an already existent module so that the lyrics are synchronized with the video. That's assuming that the lyrics are obtained separately from the YouTube video. Most music videos in my experience don't have lyrics, so this greatly enlarges the lyrics database. I learned about [SwagLyrics](https://github.com/SwagLyrics) in #10 for a different reason, but it also seems to have a module to sync the lyrics in real time: https://github.com/SwagLyrics/autosynch
> 
> I really don't know how it works, or if it's usable outside that repo, but it sounds really cool. The devs @SwagLyrics, @chriswang030 and @aadibajpai might shine some light about this. There's also another problem: the audio data provided to the module has been downloaded **beforehand**. If it were to be used in Vidify, it would have to be in real time, like what the Work In Progress [audio synchronization](https://github.com/vidify/audiosync) module does.
> 
> This could also be troublesome depending on the implementation, because Vidify already has an audio synchronization module which runs in the background, and could cause lag depending on the system Vidify runs on.

This looks really cool! Back in the day (before I had a spotify account) I used a media player called clementine which had a similar feature. The lyrics would sort of auto-scroll along. I think it worked by using the length of the track and the number of lines in the lyrics to determine a scroll speed. Simple but effective.

> ## 2
> 
> I actually didn't know that youtube-dl can also download subtitles! I haven't tried it out but it seems really easy to use in comparison to the first option.

I bumped into that feature of youtube-dl by accident, but yes it's relatively easy, and as added bonus: if the video is synchronized the subtitles (lyrics) are as well.

> Your code sketch is really helpful, thank you. To make it easier to implement in other players (maintaining modularity is important), I would add a `subtitles` method inside the players (and in the generic player in `vidify.player.generic`) to handle subtitles inside them, and then managed by the MainWindow when `on_youtubedl_success` is called.

I actually almost got it to work. I've got the `youtube.py` module to fetch both the url of the video and the captions. Not all videos have captions but for those that do it works. I had a little problem with the `.emit()` function only accepting one argument for some reason. But I fixed it by combining both strings into a single string, to be separated again by `.split()` later. Currently I'm stuck with this error for some reason:
```
File "/home/andrew/Storage/Github/spotify-music-videos/vidify/player/__init__.py", line 61, in initialize_player
obj = cls()
TypeError: __init__() missing 1 required positional argument: 'subs'
```

I've got it to get both urls to `window.py`, and then both urls to `vlc.py` and `mpv.py` What's missing is to also get `config.subs` there somehow (for the `if statement`), that's where I get that error :(

Anyway, this is beyond my python-skills, so I'll just leave the patch here. It has to be in `.zip` because otherwise github doesn't let me upload it for some reason.

[subs.zip](https://github.com/marioortizmanero/spotify-music-videos/files/4032585/subs.zip)

**Comment by marioortizmanero** [comment]
> This looks really cool! Back in the day (before I had a spotify account) I used a media player called clementine which had a similar feature. The lyrics would sort of auto-scroll along. I think it worked by using the length of the track and the number of lines in the lyrics to determine a scroll speed. Simple but effective.

Oh I know about clementine, that's a very good third option, too.

> I bumped into that feature of youtube-dl by accident, but yes it's relatively easy, and as added bonus: if the video is synchronized the subtitles (lyrics) are as well.

Yes that's the best part! I have to do some research on how many songs have subtitles, because it would really be the best.

> I had a little problem with the .emit() function only accepting one argument for some reason. But I fixed it by combining both strings into a single string, to be separated again by .split() later.

You probably weren't using the signals correctly. [When you declare them as class attributes](https://github.com/marioortizmanero/spotify-music-videos/blob/next/vidify/youtube.py#L20) (at the top, not in the `__init__` method), you can specify the types and number of parameters taken, like `Signal(str, str, float)`. And when you connect this signal to a function, you have to make sure that said option is defined as a `@Slot(str, str, float)` function with 3 parameters so that they are passed correctly.

The error you get is because the players are obtained generically in [`initialize_player`](https://github.com/marioortizmanero/spotify-music-videos/blob/next/vidify/player/__init__.py#L39), so that both VLC and mpv can be initialized the same way. I haven't read the patch in detail, but you modified the parameters that the players take, and when it tries to initialize the class in the line 60, but doesn't have the parameter, it raises an error. You can either make the `subs` parameter optional with `subs = None`, and initialize them later on in the GUI, or modify the `PlayerData` structure to handle this new behaviour.

I hope I explained myself well enough. If you have any questions go ahead and ask. Anyway, I'll work on this myself some other day and try to do it myself (you can give it a try yourself too if you want).

**Comment by AndrewAmmerlaan** [comment]
> You probably weren't using the signals correctly. When you declare them as class attributes (at the top, not in the __init__ method), you can specify the types and number of parameters taken, like Signal(str, str, float). And when you connect this signal to a function, you have to make sure that said option is defined as a @Slot(str, str, float) function with 3 parameters so that they are passed correctly.

Thank you, that was indeed the problem, I got it working a bit better now.

> The error you get is because the players are obtained generically in initialize_player, so that both VLC and mpv can be initialized the same way. I haven't read the patch in detail, but you modified the parameters that the players take, and when it tries to initialize the class in the line 60, but doesn't have the parameter, it raises an error. You can either make the subs parameter optional with subs = None, and initialize them later on in the GUI, or modify the PlayerData structure to handle this new behaviour.

I just got rid of the `subs: bool` there, because it is not necessary to parse that as well. If `subs = False` then `subsurl = None` so I can just use `if subsurl:` instead of `if subs:` after `subsurl` has been set. It's almost working now, the problem now arises with actually adding the subtitle track to vlc/mpv. I now have this for vlc and mpv respectively:
```
    def start_video(self, media: str, subs: str, is_playing: bool = True) -> None:
        logging.info("Starting new video")

        if CURRENT_PLATFORM in (Platform.LINUX, Platform.BSD):
            self._player.set_xwindow(self.winId())
        elif CURRENT_PLATFORM == Platform.WINDOWS:
            self._player.set_hwnd(self.winId())
        elif CURRENT_PLATFORM == Platform.MACOS:
            self._player.set_nsobject(int(self.winId()))

        self._media = self._vlc.media_new(media)
        if subs:
            self._media.slaves_add(0, 4, subs)
        self._media.get_mrl()
        self._player.set_media(self._media)
        # VLC starts paused
        if is_playing:
            self.pause = False
```
```
    def start_video(self, media: str, subs: str, is_playing: bool = True) -> None:
        logging.info("Started new video")

        if subs:
            self._mpv.sub_add(subs)
        self._mpv.play(media)
        # Mpv starts automatically playing the video
        if not is_playing:
            self.pause = True
```

Vlc plays, but without subs, and prints this as a warning:
```
[00007efca84c7060] ps demux warning: this does not look like an MPEG PS stream, continuing anyway
[0000560b27c7ebe0] main input error: slave[0] doesn't like DEMUX_GET_TIME -> EOF
[00007efc9008f380] vaapi_filters filter warning: Using SW chroma filter for 2048x858 VAOP -> I420
```
For some reason it expects it to be a MPEG stream, the manual says this:
```

LIBVLC_API int libvlc_media_slaves_add ( 
 libvlc_media_t * | p_md,
 libvlc_media_slave_type_t | i_type,
 unsigned int | i_priority,
 const char * | psz_uri
 )


p_md | media descriptor object
-- | --
i_type | subtitle or audio
i_priority | from 0 (low priority) to 4 (high priority)
psz_uri | Uri of the slave (should contain a valid scheme).
```
It isn't exactly clear to me, what the `I_type` integer is supposed to be, and I'm also not sure I got `psz_url` correct. `should contain a valid scheme` is not very helpful, as it doesn't tell me what a 'valid' scheme is. `.add_options(f"sub-file={subs}")` doesn't work because it will turn any arguments it is give into `file://....` which isn't what we want here because we have a `https://....`.

Mpv just completely crashes, with a very unhelpful error:
```
[10:44:46.767] INFO: Started new video
Traceback (most recent call last):
File "/home/andrew/Storage/Github/spotify-music-videos/vidify/gui/window.py", line 348, in on_yt_success
self.player.start_video(vidurl, subsurl, self.api.is_playing)
File "/home/andrew/Storage/Github/spotify-music-videos/vidify/player/mpv.py", line 86, in start_video
self._mpv.sub_add(subs)
File "/usr/lib/python3.7/site-packages/mpv.py", line 827, in sub_add
self.command('sub_add', filename.encode(fs_enc))
File "/usr/lib/python3.7/site-packages/mpv.py", line 719, in command
_mpv_command(self.handle, (c_char_p*len(args))(*args))
File "/usr/lib/python3.7/site-packages/mpv.py", line 126, in raise_for_ec
raise ex(ec, *args)
SystemError: ('Error running mpv command', -12, (<MpvHandle object at 0x7f02bca600e0>, <mpv.c_char_p_Array_3 object at 0x7f02bca60170>))
zsh: abort (core dumped)  python vidify --subs --debug --player mpv
```

**Comment by AndrewAmmerlaan** [comment]
Okay so it turns out it is a bit more complex than I thought it would be.

Vlc seems not to like subtitles from url after all, I thought it worked yesterday but I must have been mistaken because I repeatedly tried to add subs from url today and it's not working. I figured I could just use `tempfile.NamedTemporaryFile` to write a file from the url. But the file that it writes is a `.ttml` (xml) file. And vlc doesn't like these files, it needs to be converted to `.vtt` first. Luckily youtube-dl does this automatically if you ask it to download the subs. `youtube-dl --all-subs url --skip-download` downloads the captions (`.vtt`) but not the video.

Therefore, my approach (obtaining and parsing the caption url) doesn't work.
What would work is:
1) `youtube-dl --list-subs url` (find the correct language: try in order: $LANG, 'en', whatever the first entry is. If no subs: `subs = None`)
2) youtube-dl url --skip-download --write-sub --sub-lang 'language from 1)' (download as tempfile, is automatically converted to `.vtt` format)
3) add subs `self._media.slaves_add(0, 4, file.name)` and `self._mpv.sub_add(subs)`

**Comment by AndrewAmmerlaan** [comment]
I'm very happy to announce that it is working!!!

![Screenshot_20200108_181135](https://user-images.githubusercontent.com/8460628/71999777-509e3f80-3242-11ea-9db6-642724b2c867.png)

That's mpv, this is vlc:

![Screenshot_20200108_181242](https://user-images.githubusercontent.com/8460628/71999883-79bed000-3242-11ea-98a5-f0a90301530a.png)

[Here's one of the video's](https://www.youtube.com/watch?v=yA40QEzFdko) I tested with, it's in Dutch so it will be a load of nonsense if you don't speak Dutch. However, there are English subtitles.

It even works with different languages by running e.g.  `export LANG='nl':

![Screenshot_20200108_184041](https://user-images.githubusercontent.com/8460628/72001764-60b81e00-3246-11ea-86c7-4eb156dda315.png)

The only thing I haven't figured out yet is how to remove the temporary files after the song has ended. It downloads the subtitles as a `NamedTemporaryFile()`, but somehow these files should be removed again once the they are no longer necessary.

Anyway here's my patch
[subs.zip](https://github.com/marioortizmanero/spotify-music-videos/files/4036545/subs.zip)

Also, I was playing songs on repeat a lot to test this. And I noticed the video isn't restarted when a song is on repeat. It will keep playing until the video ends and just show a black screen after. Is there maybe a way the video could be looped continuously as long as the same song is playing?
